import {
  AlignLeft,
  Badge,
  BicepsFlexed,
  Biohazard,
  BrainCircuit,
  Bug,
  Earth,
  Eclipse,
  Flame,
  Ghost,
  Heart,
  Leaf,
  ListOrdered,
  Mountain,
  Origami,
  Rabbit,
  Rocket,
  Shield,
  ShieldCheck,
  ShieldPlus,
  Skull,
  Snowflake,
  WandSparkles,
  Waves,
  Zap,
} from "lucide-react";

export const pokemonIcons: { [key: string]: JSX.Element } = {
  Normal: <Badge className="text-amber-400" />,
  Fire: <Flame className="text-amber-400" />,
  Water: <Waves className="text-amber-400" />,
  Grass: <Leaf className="text-amber-400" />,
  Electric: <Zap className="text-amber-400" />,
  Ice: <Snowflake className="text-amber-400" />,
  Fighting: <BicepsFlexed className="text-amber-400" />,
  Poison: <Biohazard className="text-amber-400" />,
  Ground: <Earth className="text-amber-400" />,
  Flying: <Rocket className="text-amber-400" />,
  Psychic: <BrainCircuit className="text-amber-400" />,
  Bug: <Bug className="text-amber-400" />,
  Rock: <Mountain className="text-amber-400" />,
  Ghost: <Ghost className="text-amber-400" />,
  Dragon: <Origami className="text-amber-400" />,
  Dark: <Eclipse className="text-amber-400" />,
  Steel: <ShieldPlus className="text-amber-400" />,
  Fairy: <WandSparkles className="text-amber-400" />,
  all: <AlignLeft className="text-amber-400" />,
};

export const pokemonStatIcons: { [key: string]: JSX.Element } = {
  Hp: <Heart className="text-amber-400" />,
  Attack: <BicepsFlexed className="text-amber-400" />,
  Defense: <Shield className="text-amber-400" />,
  Special_Attack: <Skull className="text-amber-400" />,
  Special_Defense: <ShieldCheck className="text-amber-400" />,
  Speed: <Rabbit className="text-amber-400" />,
  number: <ListOrdered className="text-amber-400" />,
};
